# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty



# Setup
title:            Intersex 101
tagline:          'A Jekyll theme'
description:      'A project that aims to spread accurate and scientific awareness about what DSD means'
url:              https://intersex101.com

author:
  name:           'SJ Guo'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
