# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Intersex 101
tagline:          'A Jekyll theme'
description:      'A project that aims to spread accurate and scientific awareness about what DSD means'
url:              https://intersex101.com
baseurl:          /

author:
  name:           'SJ Guo'
